---
- name: Allow TCP port 22.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT
    comment: Accept SSH connections

- name: Allow TCP port 80.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    comment: Accept http