---
- name: Allow TCP port 22.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
    comment: Accept SSH connections

- name: Allow TCP port 80.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    comment: Accept http

- name: Save iptables
  command: sudo iptables-save

