network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s3:
            dhcp4: no
            dhcp6: no
            addresses: [10.0.0.2/16]
            gateway4: 10.0.0.1
            nameservers:
              addresses: [1.1.1.1]
              search: [ anydomain.com ]
