---
- name: Provision node server
  hosts: all
  remote_user: prov
  become: True
  gather_facts: True
  vars:
    - nginx_config: "nginx_django_config.yml"
  roles:
    - network
    - nginx
    - posgresql